name: Publish NuGet Package

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build 

    - name: Pack NuGet package
      run: dotnet pack --output ./artifacts

    - name: Publish NuGet package
      uses: nuget/publish@1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }} 
        nuget-version: '8.0.x'  # Adjust NuGet version as needed
        nuget-package: './artifacts/*.nupkg'
